### ISSUE TITLE
compile issue

### ISSUE THREAD

**Issue by AnonyK1** [ustcadsl/diffkv#1]
- Thanks for sharing your greate work!
- When build DiffKV, I met errors
```
[root@localhost build]# make titan -j
make: *** No rule to make target 'titan'.  Stop.
```

**Comment by ZacharyLiu-CS** [comment]
Can you provide more details like hardware configuration, system version, dependent libraries? It is hard to get the cause of the problem from limited information.

**Comment by BaronStack** [comment]
Maybe you should to check  if the cmake execute successful , after that the makefile will be produced.

**Comment by yliu634** [comment]
Yes, I have the same problem, I think @ZacharyLiu-CS you can use an empty machine to execute the code, and there is no titan target in cmake. even though I just make -j, there are a lot of errors contained in your code.

**Comment by zjs1224522500** [comment]
Which version of Titan is implemented based for DiffKV?

**Comment by zjs1224522500** [comment]
Which version of Titan is implemented based for DiffKV?

**Comment by cscetbon** [comment]
> * Thanks for sharing your great work!
> * When build DiffKV, I met errors
> 
> ```
> [root@localhost build]# make titan -j
> make: *** No rule to make target 'titan'.  Stop.
> ```

It's clear that there is no titan target in the Makefile. What's the reason to build titan here ? Is it to compare diffkv to titan ? I would just build it from titan

> Which version of Titan is implemented based for DiffKV?

@zjs1224522500 branch 6.4.tikv based on TiKV 6.4 RocksDB

**Comment by cscetbon** [comment]
@ZacharyLiu-CS I also have issues compiling diffkv, it fails when it tries to link against titan. I installed the right version that is working on top of tikv/rocksdb 6.4.tikv but maybe it's more recent than when you wrote your code and that's why the linking is failing now.

```
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libtitan.a(db_impl_gc.cc.o): in function `rocksdb::titandb::TitanDBImpl::BackgroundCallGC()':
db_impl_gc.cc:(.text+0xe5b): undefined reference to `rocksdb::SyncPoint::GetInstance()'
/usr/bin/ld: db_impl_gc.cc:(.text+0xea1): undefined reference to `rocksdb::SyncPoint::Process(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void*
)'
/usr/bin/ld: db_impl_gc.cc:(.text+0xf54): undefined reference to `rocksdb::SyncPoint::GetInstance()'
/usr/bin/ld: db_impl_gc.cc:(.text+0xf9a): undefined reference to `rocksdb::SyncPoint::Process(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void*
)'
..
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libtitan.a(blob_file_reader.cc.o): in function `rocksdb::titandb::BlobFileReader::Get(rocksdb::ReadOptions const&, rocksdb::titandb::BlobHandle const&, rocksdb::titandb::BlobRecord*, rocksdb::PinnableSlice*)':
blob_file_reader.cc:(.text+0xd26): undefined reference to `rocksdb::SyncPoint::GetInstance()'
/usr/bin/ld: blob_file_reader.cc:(.text+0xd60): undefined reference to `rocksdb::SyncPoint::Process(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void*)'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libtitan.a(blob_file_set.cc.o): in function `rocksdb::titandb::BlobFileSet::LogAndApply(rocksdb::titandb::VersionEdit&)':
blob_file_set.cc:(.text+0x1fe9): undefined reference to `rocksdb::SyncPoint::GetInstance()'
/usr/bin/ld: blob_file_set.cc:(.text+0x202f): undefined reference to `rocksdb::SyncPoint::Process(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void*)'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libtitan.a(blob_file_set.cc.o):(.data.rel.ro._ZTIN7rocksdb7titandb11LogReporterE[_ZTIN7rocksdb7titandb11LogReporterE]+0x10): undefined reference to `typeinfo for rocksdb::log::Reader::Reporter'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libtitan.a(blob_format.cc.o): in function `rocksdb::titandb::BlobDecoder::DecodeRecord(rocksdb::Slice*, rocksdb::titandb::BlobRecord*, rocksdb::titandb::OwnedSlice*)':
blob_format.cc:(.text+0x573): undefined reference to `rocksdb::SyncPoint::GetInstance()'
/usr/bin/ld: blob_format.cc:(.text+0x5b2): undefined reference to `rocksdb::SyncPoint::Process(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void*)'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libtitan.a(blob_gc_job.cc.o): in function `rocksdb::titandb::BlobGCJob::Finish()':
blob_gc_job.cc:(.text+0x248d): undefined reference to `rocksdb::SyncPoint::GetInstance()'
/usr/bin/ld: blob_gc_job.cc:(.text+0x24c7): undefined reference to `rocksdb::SyncPoint::Process(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void*)'
/usr/bin/ld: blob_gc_job.cc:(.text+0x26e2): undefined reference to `rocksdb::SyncPoint::GetInstance()'
/usr/bin/ld: blob_gc_job.cc:(.text+0x271c): undefined reference to `rocksdb::SyncPoint::Process(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void*)'
collect2: error: ld returned 1 exit status
```

Also I see you use a specific version of [tikv-rocksdb](https://github.com/JiayuZzz/rocksdb/tree/d672659061091d506289b1379b3128f3f93c82af) but your version is missing monitoring/statistics_impl.h that is needed by titan to build so I can't use the same when building titan
https://github.com/JiayuZzz/rocksdb/tree/diffkv/monitoring
https://github.com/tikv/titan/blob/tikv-6.1/src/titan_stats.cc#L6

So the question is why is it failing and which version of titan did you use exactly cause it doesn't tell in your repo. Can we update that version with the current one to avoid this issue when linking ? or build the same version you used maybe instead of trying to link to a more recent I guess ?

**Comment by ZacharyLiu-CS** [comment]
> Which version of Titan is implemented based for DiffKV?

It starts from 715dbd69f1c8ea1d42d2b8edb7a6f2a4fd15ca33 in Titan master branch.

**Comment by ZacharyLiu-CS** [comment]
> @ZacharyLiu-CS I also have issues compiling diffkv, it fails when it tries to link against titan. I installed the right version that is working on top of tikv/rocksdb 6.4.tikv but maybe it's more recent than when you wrote your code and that's why the linking is failing now.
> 
> ```
> /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libtitan.a(db_impl_gc.cc.o): in function `rocksdb::titandb::TitanDBImpl::BackgroundCallGC()':
> db_impl_gc.cc:(.text+0xe5b): undefined reference to `rocksdb::SyncPoint::GetInstance()'
> /usr/bin/ld: db_impl_gc.cc:(.text+0xea1): undefined reference to `rocksdb::SyncPoint::Process(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void*
> )'
> /usr/bin/ld: db_impl_gc.cc:(.text+0xf54): undefined reference to `rocksdb::SyncPoint::GetInstance()'
> /usr/bin/ld: db_impl_gc.cc:(.text+0xf9a): undefined reference to `rocksdb::SyncPoint::Process(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void*
> )'
> ..
> /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libtitan.a(blob_file_reader.cc.o): in function `rocksdb::titandb::BlobFileReader::Get(rocksdb::ReadOptions const&, rocksdb::titandb::BlobHandle const&, rocksdb::titandb::BlobRecord*, rocksdb::PinnableSlice*)':
> blob_file_reader.cc:(.text+0xd26): undefined reference to `rocksdb::SyncPoint::GetInstance()'
> /usr/bin/ld: blob_file_reader.cc:(.text+0xd60): undefined reference to `rocksdb::SyncPoint::Process(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void*)'
> /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libtitan.a(blob_file_set.cc.o): in function `rocksdb::titandb::BlobFileSet::LogAndApply(rocksdb::titandb::VersionEdit&)':
> blob_file_set.cc:(.text+0x1fe9): undefined reference to `rocksdb::SyncPoint::GetInstance()'
> /usr/bin/ld: blob_file_set.cc:(.text+0x202f): undefined reference to `rocksdb::SyncPoint::Process(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void*)'
> /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libtitan.a(blob_file_set.cc.o):(.data.rel.ro._ZTIN7rocksdb7titandb11LogReporterE[_ZTIN7rocksdb7titandb11LogReporterE]+0x10): undefined reference to `typeinfo for rocksdb::log::Reader::Reporter'
> /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libtitan.a(blob_format.cc.o): in function `rocksdb::titandb::BlobDecoder::DecodeRecord(rocksdb::Slice*, rocksdb::titandb::BlobRecord*, rocksdb::titandb::OwnedSlice*)':
> blob_format.cc:(.text+0x573): undefined reference to `rocksdb::SyncPoint::GetInstance()'
> /usr/bin/ld: blob_format.cc:(.text+0x5b2): undefined reference to `rocksdb::SyncPoint::Process(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void*)'
> /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libtitan.a(blob_gc_job.cc.o): in function `rocksdb::titandb::BlobGCJob::Finish()':
> blob_gc_job.cc:(.text+0x248d): undefined reference to `rocksdb::SyncPoint::GetInstance()'
> /usr/bin/ld: blob_gc_job.cc:(.text+0x24c7): undefined reference to `rocksdb::SyncPoint::Process(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void*)'
> /usr/bin/ld: blob_gc_job.cc:(.text+0x26e2): undefined reference to `rocksdb::SyncPoint::GetInstance()'
> /usr/bin/ld: blob_gc_job.cc:(.text+0x271c): undefined reference to `rocksdb::SyncPoint::Process(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void*)'
> collect2: error: ld returned 1 exit status
> ```
> 
> Also I see you use a specific version of [tikv-rocksdb](https://github.com/JiayuZzz/rocksdb/tree/d672659061091d506289b1379b3128f3f93c82af) but your version is missing monitoring/statistics_impl.h that is needed by titan to build so I can't use the same when building titan https://github.com/JiayuZzz/rocksdb/tree/diffkv/monitoring https://github.com/tikv/titan/blob/tikv-6.1/src/titan_stats.cc#L6
> 
> So the question is why is it failing and which version of titan did you use exactly cause it doesn't tell in your repo. Can we update that version with the current one to avoid this issue when linking ? or build the same version you used maybe instead of trying to link to a more recent I guess ?

Are these error messages generated when compiling the static library diffkv, or when you try to compile libtitan.a from tikv/tian, because our work diffkv is developed based on a fork of titan (starting from 715dbd69f1c8ea1d42d2b8edb7a6f2a4fd15ca33), and in order to implement our contributions, a specific rocksdb version is also required (see in [rocksdb](https://github.com/JiayuZzz/rocksdb/tree/d672659061091d506289b1379b3128f3f93c82af) ). So the point is that if you build the code, you don't need to link to titan, you only need to link to rocksdb because diffkv works as a plugin of rocksdb.
